# Generated by Django 6.0.4 on 2026-04-26 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_universe', '0003_pirateitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='island',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mi_universe.island'),
            preserve_default=False,
        ),
    ]
