# Generated by Django 6.0.4 on 2026-04-26 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_universe', '0004_character_island'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='island',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='pirateitem',
            name='image_url',
        ),
    ]
