# Generated by Django 6.0.4 on 2026-04-26 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_universe', '0005_remove_character_image_url_remove_island_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='image_file',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='island',
            name='image_file',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='pirateitem',
            name='image_file',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
