# Generated by Django 6.0.4 on 2026-04-27 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_universe', '0006_character_image_file_island_image_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('release_year', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='island',
            name='image_file',
        ),
        migrations.AddField(
            model_name='island',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='islands/'),
        ),
        migrations.AddField(
            model_name='island',
            name='parent_island',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_islands', to='mi_universe.island'),
        ),
        migrations.AddField(
            model_name='island',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='islands', to='mi_universe.game'),
        ),
    ]
