# Generated by Django 6.0.4 on 2026-04-27 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_universe', '0007_game_remove_island_image_file_island_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='island',
            name='game',
        ),
        migrations.RemoveField(
            model_name='island',
            name='image',
        ),
        migrations.RemoveField(
            model_name='island',
            name='parent_island',
        ),
        migrations.AddField(
            model_name='island',
            name='image_file',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.DeleteModel(
            name='Game',
        ),
    ]
