# Generated by Django 6.0.4 on 2026-04-28 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_universe', '0009_characterimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CharacterImage',
        ),
    ]
