# Generated by Django 6.0.4 on 2026-05-30 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_universe', '0010_delete_characterimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='island',
            name='game',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
    ]
