# Generated by Django 6.0.4 on 2026-05-30 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_universe', '0012_alter_island_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='island',
            name='sub_islands',
            field=models.ManyToManyField(blank=True, related_name='parent_islands', to='mi_universe.island'),
        ),
        migrations.AlterField(
            model_name='island',
            name='game',
            field=models.CharField(choices=[('Unknown', 'Unknown'), ('The Secret of Monkey Island', 'The Secret of Monkey Island'), ("Monkey Island 2 – LeChuck's Revenge", "Monkey Island 2 – LeChuck's Revenge"), ('The Curse of Monkey Island', 'The Curse of Monkey Island'), ('Escape from Monkey Island', 'Escape from Monkey Island'), ('Tales of Monkey Island', 'Tales of Monkey Island'), ('Return to Monkey Island', 'Return to Monkey Island')], max_length=100),
        ),
    ]
