# Generated by Django 6.0.4 on 2026-05-30 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_universe', '0013_island_sub_islands_alter_island_game'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='island',
            name='sub_islands',
        ),
    ]
