# Generated by Django 6.0.4 on 2026-05-11 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_cartitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='image',
            new_name='image_file',
        ),
    ]
